import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { Header, Footer } from '../components/Chrome';
import { PageHero, ChecklistSection, MiniForm, ClosingCta, StatsBar } from '../components/content';
import { FaqList } from '../components/sections';
import { useSiteMotion } from '../hooks/useSiteMotion';
import { useSeo } from '../hooks/useSeo';

const DEMO_FAQ = [
  [
    'Will this break our current EMR?',
    'Nope. The platform wraps right around your existing setup. No data migrations required.',
  ],
  [
    'Can it handle heavy regional accents?',
    'Absolutely. The system is heavily trained to accurately process Indian-accented clinical English and Tamil dictations.',
  ],
  [
    'How do you handle data privacy?',
    "Every single word generated by the AI links directly back to the physician's exact audio file. It cannot invent clinical facts.",
  ],
];

export default function Demo() {
  useSeo(
    'Book a Medibytes Demo | AI Healthcare Assistant',
    'See our AI healthcare assistant in action. Book a fast walkthrough to learn how we cut discharge times and reduce claim denials without replacing your HMIS.'
  );
  useSiteMotion({ pinWorkflow: false, scrubVision: false, heroIntro: true });

  return (
    <>
      <Header active="demo" />
      <main id="main">
        <PageHero
          id="demo-heading"
          eyebrow="LIVE WALKTHROUGH"
          lines={[
            { text: 'Give Your Doctors' },
            { text: 'Their Time Back.', green: true },
          ]}
          sub="Watch Medibytes act as an invisible intelligence layer over your existing HMIS. Book your live walkthrough below and let's speed up your clinical workflows."
          actions={
            <a className="button primary" href="#booking-form">
              Lock In My Demo <ArrowRight aria-hidden="true" />
            </a>
          }
        />

        <StatsBar
          label="What the walkthrough covers"
          stats={[
            ['activity', '30-minute live dashboard tour'],
            ['file-text', 'Discharges: 40 → 7 minutes'],
            ['shield-check', 'Zero-pressure fit check'],
          ]}
        />

        <section className="faq container section" id="booking-form">
          <div className="faq-heading reveal">
            <div className="eyebrow">BOOKING</div>
            <h2>
              Grab your
              <br />
              time slot.
            </h2>
          </div>
          <div className="faq-list reveal">
            <p style={{ maxWidth: 560, marginBottom: 22 }}>
              Use the calendar embed to lock in a slot, or drop your details into the short form
              below and we will handle the logistics.
            </p>
            <MiniForm
              idPrefix="demo"
              button="Lock In My Demo"
              successMsg="Slot request noted — we will confirm your walkthrough shortly at your work email."
              fields={{
                name: { label: 'Name', hint: 'Who are we speaking with?' },
                email: { label: 'Work Email', hint: 'Where should we send the invite?' },
                facility: {
                  label: 'Facility Type',
                  hint: 'e.g., 500-Bed Hospital',
                  placeholder: 'e.g., 500-Bed Hospital',
                },
                whatsapp: { label: 'WhatsApp Number', hint: 'For quick updates.' },
              }}
            />
          </div>
        </section>

        <ChecklistSection
          id="what-to-expect"
          eyebrow="THE CALL"
          title="What to expect on our call."
          copy="No high-pressure sales pitch. Just a practical look at fixing administrative bottlenecks."
          items={[
            [
              'activity',
              'Fast, 30-Minute Walkthrough',
              'We jump straight into the live dashboard.',
            ],
            [
              'scan-line',
              'Custom Workflow Mapping',
              'We pinpoint exactly where your staff loses the most time.',
            ],
            [
              'check',
              'Zero Pressure',
              "If the tech isn't a fit for your system, we will tell you directly.",
            ],
          ]}
        />

        <section className="faq container section" style={{ paddingTop: 0 }}>
          <div className="faq-heading reveal">
            <div className="eyebrow">QUICK ANSWERS</div>
            <h2>
              Before you
              <br />
              book.
            </h2>
          </div>
          <div className="faq-list reveal">
            <FaqList items={DEMO_FAQ} />
            <div className="teaser-cta">
              <Link className="text-button" to="/vision">
                Browse All FAQs <ArrowRight aria-hidden="true" />
              </Link>
            </div>
          </div>
        </section>

        <ClosingCta
          eyebrow="READY WHEN YOU ARE"
          title="Ready to upgrade your floor?"
          copy="Cut those 40-minute discharge summaries down to just 7 minutes. Let's get started."
          button="Schedule Your Session Now"
        />
      </main>
      <Footer />
    </>
  );
}
